# Generated by Django 5.2.2 on 2025-07-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_description_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
