# Generated by Django 5.2.2 on 2025-07-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_soft_deleted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="deleted_at",
        ),
    ]
