# Generated by Django 5.2.2 on 2025-07-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_deleted_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="soft_deleted_at",
            new_name="deleted_at",
        ),
    ]
