# Generated by Django 5.2.2 on 2025-08-07 04:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="avatar_url",
        ),
        migrations.RemoveField(
            model_name="community",
            name="banner_url",
        ),
        migrations.AddField(
            model_name="community",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="community_avatars"
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="banner",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="community_banners"
            ),
        ),
    ]
