# Generated by Django 5.2.3 on 2025-07-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
