# Generated by Django 5.2.2 on 2025-08-16 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_communities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="communitymember",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="communities.community",
            ),
        ),
        migrations.AddField(
            model_name="communitymember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="communitymember",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="communities.communityrole",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="communities", to="communities.tag"
            ),
        ),
        migrations.AddIndex(
            model_name="communitymember",
            index=models.Index(
                fields=["community", "user"], name="community_m_communi_973737_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="communitymember",
            unique_together={("community", "user")},
        ),
    ]
