# Generated by Django 5.2.2 on 2025-08-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0002_remove_community_avatar_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="community",
            name="banner",
        ),
        migrations.AddField(
            model_name="community",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="community",
            name="banner_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
