# Generated by Django 5.2.2 on 2025-08-09 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "communities",
            "0003_remove_community_avatar_remove_community_banner_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="community",
            old_name="avatar_url",
            new_name="avatar",
        ),
        migrations.RenameField(
            model_name="community",
            old_name="banner_url",
            new_name="banner",
        ),
    ]
