# Generated by Django 5.2.2 on 2025-08-16 01:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora en que se creó la relación.",
                        verbose_name="Fecha de Creación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguimiento de Usuario",
                "verbose_name_plural": "Seguimientos de Usuarios",
                "db_table": '"users"."user_follows"',
            },
        ),
    ]
