# Generated by Django 5.2.3 on 2025-06-23 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de Usuario',
                'verbose_name_plural': 'Seguimientos de Usuarios',
                'db_table': 'user_follows',
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
            ],
            options={
                'verbose_name': 'Alias de Seguimiento',
                'verbose_name_plural': 'Alias de Seguimientos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('social_follow.userrelationship',),
        ),
        migrations.AddIndex(
            model_name='userrelationship',
            index=models.Index(fields=['follower'], name='user_follow_followe_a0b992_idx'),
        ),
        migrations.AddIndex(
            model_name='userrelationship',
            index=models.Index(fields=['following'], name='user_follow_followi_eaf074_idx'),
        ),
        migrations.AddConstraint(
            model_name='userrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='prevent_self_follow'),
        ),
        migrations.AlterUniqueTogether(
            name='userrelationship',
            unique_together={('follower', 'following')},
        ),
    ]
