# Generated by Django 5.2.2 on 2025-08-16 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("social_follow", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userrelationship",
            name="follower",
            field=models.ForeignKey(
                help_text="Usuario que sigue a otro.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario Seguidor",
            ),
        ),
        migrations.AddField(
            model_name="userrelationship",
            name="following",
            field=models.ForeignKey(
                help_text="Usuario que está siendo seguido.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario Seguido",
            ),
        ),
        migrations.CreateModel(
            name="UserFollow",
            fields=[],
            options={
                "verbose_name": "Alias de Seguimiento",
                "verbose_name_plural": "Alias de Seguimientos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("social_follow.userrelationship",),
        ),
        migrations.AddIndex(
            model_name="userrelationship",
            index=models.Index(
                fields=["follower"], name="user_follow_followe_a0b992_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrelationship",
            index=models.Index(
                fields=["following"], name="user_follow_followi_eaf074_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(("follower", models.F("following")), _negated=True),
                name="prevent_self_follow",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrelationship",
            unique_together={("follower", "following")},
        ),
    ]
